version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mongodbVSCodePlaygroundDB

volumes:
  mongodb_data: 